language: python
python:
  - "3.8"

branches:
  only:
    - dev

install:
  - pip install -r ./requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - cd test
  - pytest --cov=./

after_success: 
  - coveralls
notifications:
  on_success: always
cache: pip
