name: mltools_viewer
description: 使用flutter编写的数据标注/增广的可视化工具

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.0
  provider: ^6.0.3
  taichi:
    git:
        url: https://github.com/guchengxi1994/taichi
        ref: dev
        path: taichi_core
  tuple: ^2.0.0
  path: ^1.8.1
  url_launcher: ^6.1.4
  fluttertoast: ^8.0.9
  crypto: ^3.0.2
  package_info_plus: ^1.4.3
  showcaseview: ^1.1.7
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  code_text_field: ^1.0.2
  clipboard: ^0.1.3
  # window_manager: ^0.2.5  # 和desktop_multi_window好像有冲突
  desktop_multi_window: ^0.1.0
  universal_html: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon2.png"
  web:
    generate: true
    image_path: "assets/icon/icon2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon2.png"
    icon_size: 48 # min:48, max:256, default: 48

deferred-components:
  - name: mltools_viewer
    libraries:
      - package:mltools_viewer/screens/image_labeling/components/image_labeling_sidemenu.dart
      - package:mltools_viewer/screens/image_labeling/components/image_labeling_right_sidemenu.dart
      - package:mltools_viewer/screens/image_labeling/components/image_labeling_workboard.dart
      - package:mltools_viewer/screens/image_labeling/image_labeling_screen.dart
      - package:mltools_viewer/screens/main_screen.dart
      - package:mltools_viewer/screens/nlp_labeling/nlp_labeling_screen.dart
      - package:mltools_viewer/screens/blank_page.dart
      - package:mltools_viewer/screens/nlp_labeling/text_annotation/text_annotation_screen.dart
      - package:mltools_viewer/screens/nlp_labeling/text_annotation/custom_text_ner_screen.dart
      - package:mltools_viewer/screens/mltools_screens/mltools_main_screen.dart
      - package:mltools_viewer/screens/mltools_screens/tools_screens/sift_screen.dart
      - package:mltools_viewer/screens/nlp_labeling/classification/nlp_classification_screen.dart

flutter:
  uses-material-design: true
  # fonts:
  #   - family: NotoSerifSC
  #     fonts:
  #       - asset: assets/font/NotoSerifSC-Regular.otf

  assets:
    - assets/icon/Check.png
  #   - images/a_dot_ham.jpeg

