name: mltools_viewer
description: 使用flutter编写的数据标注/增广的可视化工具

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  provider: ^6.0.3
  taichi:
    git:
        url: https://github.com/guchengxi1994/taichi
        ref: dev
        path: taichi_core
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

deferred-components:
  - name: mltools_viewer
    libraries:
      - package:mltools_viewer/widgets/sidemenu.dart

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

